In [1]:
'''
NUMPY:
------
Travis Oliphant
2005

'''
import numpy as np 
arr=np.array([1,2,3,4,5])
print(f"arr:{arr}")
print(type(arr))

#tuple
arr1=np.array(('a','b','c','d'))
print(f"arr1:{arr1}")
print(type(arr1))

print("-"*60)

#dimensions
arr2=np.array(50)
print(f"arr2:{arr2}")

#one dimension array
arr3=np.array([1,2,3,4,5])
print(f"arr3:{arr3}")

print("-"*60)

#two dimension array
arr4=np.array(([1,2,3],[4,5,6]))
print(arr4)

print("-"*60)

#three dimension array
arr5=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr5)

print(f"arr4:{arr4.ndim}") #gives the dimension

print("-"*60)
arr6=np.array([1,2,3,4,5], ndmin=5)
print(arr6)

print("-"*60)
arr7=np.zeros((2,3))
print(f"arr7:{arr7}")

print("-"*60)
arr8=np.zeros((2,3,4)) #2 will be the number of matrix of size 3x4
print(f"arr8:{arr8}")

print("-"*60)


arr:[1 2 3 4 5]
<class 'numpy.ndarray'>
arr1:['a' 'b' 'c' 'd']
<class 'numpy.ndarray'>
------------------------------------------------------------
arr2:50
arr3:[1 2 3 4 5]
------------------------------------------------------------
[[1 2 3]
 [4 5 6]]
------------------------------------------------------------
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
arr4:2
------------------------------------------------------------
[[[[[1 2 3 4 5]]]]]
------------------------------------------------------------
arr7:[[0. 0. 0.]
 [0. 0. 0.]]
------------------------------------------------------------
arr8:[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
------------------------------------------------------------
